"use client";

import { useEffect, useState, type CSSProperties, type ReactNode } from "react";
import { DemoRunResultSchema, processingZones, type DemoRunResult, type ProcessingZoneId } from "@/lib/compliance";
import { scenarios, type ScenarioDefinition, type ScenarioId } from "@/lib/scenarios";
import { HumanDecisionSchema, type HumanDecision } from "@/lib/schemas";

type IconName = "scale" | "arrow" | "check" | "lock" | "alert" | "file" | "gavel" | "shield" | "refresh" | "globe" | "eye" | "database";
function Icon({ name, size = 20 }: { name: IconName; size?: number }) {
  const paths: Record<IconName, ReactNode> = {
    scale:<><path d="M12 3v18M5 6h14M7 6l-4 7h8L7 6ZM17 6l-4 7h8l-4-7ZM8 21h8"/><path d="M3 13c.5 2 2 3 4 3s3.5-1 4-3M13 13c.5 2 2 3 4 3s3.5-1 4-3"/></>,
    arrow:<path d="M5 12h14M14 7l5 5-5 5"/>,check:<path d="m5 12 4 4L19 6"/>,
    lock:<><rect x="4" y="10" width="16" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3M12 14v3"/></>,
    alert:<><path d="M12 3 2.5 20h19L12 3Z"/><path d="M12 9v5M12 17.5v.1"/></>,
    file:<><path d="M6 2h8l4 4v16H6z"/><path d="M14 2v5h5M9 12h6M9 16h6"/></>,
    gavel:<><path d="m13 7 4 4M6 14l4 4M8 16l7-7M11 5l2-2 6 6-2 2M4 20h10"/></>,
    shield:<><path d="M12 3 4.5 6v5.5c0 4.7 3.1 8 7.5 9.5 4.4-1.5 7.5-4.8 7.5-9.5V6L12 3Z"/><path d="m9 12 2 2 4-4"/></>,
    refresh:<><path d="M20 7v5h-5M4 17v-5h5"/><path d="M6.1 8A7 7 0 0 1 18.5 7M17.9 16A7 7 0 0 1 5.5 17"/></>,
    globe:<><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a14 14 0 0 1 0 18M12 3a14 14 0 0 0 0 18"/></>,
    eye:<><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12Z"/><circle cx="12" cy="12" r="2.5"/></>,
    database:<><ellipse cx="12" cy="5" rx="8" ry="3"/><path d="M4 5v7c0 1.7 3.6 3 8 3s8-1.3 8-3V5M4 12v7c0 1.7 3.6 3 8 3s8-1.3 8-3v-7"/></>,
  };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden>{paths[name]}</svg>;
}

const stages = ["Case setup","Evidence split","Witnesses","Court Clerk","Jury","Human Judge","Audit report"];
const viewLabels = { evidence_first:"Evidence-first", claim_evidence:"Claim / Evidence", contradiction_first:"Contradiction-first" } as const;
const wait = (ms:number) => new Promise((resolve) => window.setTimeout(resolve,ms));
function Brand(){return <div className="brand"><span className="brand-mark"><Icon name="scale" size={23}/></span><strong>Jury<span>AI</span></strong></div>}
function Kicker({children}:{children:ReactNode}){return <div className="kicker"><span/>{children}</div>}
function Button({children,onClick,secondary=false,icon="arrow"}:{children:ReactNode;onClick:()=>void;secondary?:boolean;icon?:IconName}){return <button className={`demo-button ${secondary?"secondary":""}`} onClick={onClick}>{children}<Icon name={icon} size={18}/></button>}
function Shell({stage,scenario,mode,children}:{stage:number;scenario:ScenarioDefinition;mode?:"live"|"fallback";children:ReactNode}){
  return <main className="demo-shell"><header className="demo-header"><Brand/><div className="case-id">{scenario.title.toUpperCase()} · {scenario.caseData.id}</div><div className="header-status"><i/>{mode==="live"?"LIVE AGENTS":mode==="fallback"?"DEMO FALLBACK":"GOVERNANCE ENGINE READY"}</div></header><nav className="stage-rail" aria-label="Review progress">{stages.map((name,index)=><div key={name} className={index===stage?"active":index<stage?"done":""}><span>{index<stage?<Icon name="check" size={12}/>:index+1}</span><small>{name}</small></div>)}</nav><section className="demo-stage" key={stage}>{children}</section><footer className="demo-footer"><span>JuryAI · AI decision accountability</span><span>Prototype accelerated with IBM Bob</span></footer></main>
}

function CaseSetup({scenario,setScenario,zone,setZone,start}:{scenario:ScenarioDefinition;setScenario:(id:ScenarioId)=>void;zone:ProcessingZoneId;setZone:(id:ProcessingZoneId)=>void;start:()=>void}){
  return <div className="screen setup-screen"><section className="setup-intro"><Kicker>AI decisions deserve a trial</Kicker><h1>Put automated decisions <span>on trial.</span></h1><p>Compartmentalized testimony, independent jury voting, and accountable human oversight—through one reusable governance engine.</p><div className="platform-tags"><span>Lending</span><span>HR screening</span><span>Public sector</span></div></section><section className="setup-panel"><div className="panel-label">1 · CHOOSE A CASE</div><div className="scenario-tabs">{scenarios.map((item)=><button key={item.id} className={item.id===scenario.id?"selected":""} onClick={()=>setScenario(item.id)}><strong>{item.shortLabel}</strong><small>{item.description}</small></button>)}</div><div className="setup-grid"><div><label>PROCESSING BOUNDARY</label><select value={zone} onChange={(event)=>setZone(event.target.value as ProcessingZoneId)}>{processingZones.map((item)=><option key={item.id} value={item.id}>{item.label}</option>)}</select></div><div className="boundary-status"><Icon name="globe" size={18}/><p><strong>{processingZones.find((item)=>item.id===zone)?.location}</strong><span>Scoped summaries · stateless sessions</span></p></div></div><div className="case-summary"><div><span>AUTOMATED DECISION</span><strong>{scenario.initialDecisionLabel}</strong><small>{scenario.confidence}% confidence</small></div><div><span>SUBJECT</span><strong>{scenario.subject}</strong><small>{scenario.reason}</small></div></div><div className="input-review"><span>INPUT SUMMARY</span>{scenario.inputs.map((input)=><p key={input.label}><small>{input.label}</small><strong>{input.value}</strong></p>)}<div><Icon name="shield" size={14}/> 5 verified sources · sensitive data isolated</div></div><button className="trial-button" onClick={start}><Icon name="scale" size={22}/> PUT DECISION ON TRIAL <Icon name="arrow" size={20}/></button></section></div>
}

function EvidenceSplit({scenario}:{scenario:ScenarioDefinition}){
  return <div className="screen centered-screen"><Kicker>Compartmentalized evidence</Kicker><h1>Independent first. <span>Synthesis second.</span></h1><p className="lead">The same case is broken into minimum-necessary, sealed packets.</p><div className="evidence-split">{scenario.evidenceLabels.map((label,index)=><article key={label} style={{"--i":index} as CSSProperties}><span>EV-0{index+1}</span><strong>{label}</strong><small><Icon name="lock" size={11}/> FRESH SESSION</small></article>)}</div><div className="boundary-note"><Icon name="globe" size={15}/> Processing boundary enforced at packet creation</div></div>
}

function Witnesses({scenario}:{scenario:ScenarioDefinition}){
  const roles=[{name:"Decision Witness",packet:"EV-01 · EV-02 · EV-03",icon:"check" as const},{name:"Fact Checker",packet:"EV-02 · EV-03 · EV-04",icon:"alert" as const},{name:"Bias & Privacy Challenger",packet:"EV-05 + permitted metadata",icon:"alert" as const}];
  return <div className="screen centered-screen"><Kicker>Independent AI witnesses</Kicker><h1>Different questions. <span>No shared context.</span></h1><div className="witness-grid">{roles.map((role,index)=><article key={role.name}><div className="witness-top"><span>0{index+1}</span><small><Icon name="lock" size={11}/> SEALED INPUT</small></div><h2>{role.name}</h2><div className="packet-line">Allowed: {role.packet}</div><p className={index===0?"positive":"warning"}><Icon name={role.icon} size={19}/>{scenario.witnessFindings[index]}</p><small className="blocked">Blocked: other testimony · jury conclusions</small></article>)}</div><p className="stage-note"><Icon name="shield" size={15}/> Least privilege is visible, enforced, and recorded.</p></div>
}

function CourtClerk({run}:{run:DemoRunResult|null}){
  const packet=run?.review.court.casePacket;
  return <div className="screen clerk-screen"><section><Kicker>Deterministic Court Clerk</Kicker><h1>Evidence sealed.<br/><span>Case assembled.</span></h1><p>Only validated structured findings move forward. Raw reasoning and prior conversations do not.</p><div className="clerk-checks"><span><Icon name="check" size={15}/> Provenance preserved</span><span><Icon name="check" size={15}/> Findings deduplicated</span><span><Icon name="check" size={15}/> PII excluded</span></div></section><section className="case-file"><div><Icon name="file" size={32}/><span>NEUTRAL CASEPACKET</span><strong>{packet?.packetId??"ASSEMBLING"}</strong></div><dl><div><dt>Verified findings</dt><dd>{packet?.verifiedFindings.length??5}</dd></div><div><dt>Contradictions</dt><dd>{packet?.contradictions.length??1}</dd></div><div><dt>Risk flags</dt><dd>{packet?.riskFlags.length??2}</dd></div><div><dt>Evidence links</dt><dd>{packet?.evidenceReferences.length??5}</dd></div></dl><small><Icon name="lock" size={12}/> ADMISSIBLE STRUCTURED EVIDENCE ONLY</small></section></div>
}

function Jury({run,revealed,reveal,next}:{run:DemoRunResult|null;revealed:boolean;reveal:()=>void;next:()=>void}){
  useEffect(()=>{if(revealed)return;const timer=window.setTimeout(reveal,850);return()=>window.clearTimeout(timer)},[revealed,reveal]);
  const votes=run?.review.court.jurorVotes??[{jurorId:"J1",view:"evidence_first",vote:"overturn"},{jurorId:"J2",view:"claim_evidence",vote:"overturn"},{jurorId:"J3",view:"contradiction_first",vote:"human_review"}] as const;
  const verdict=run?.review.court.juryVerdict;
  return <div className="screen jury-screen"><Kicker>Independent Jury</Kicker><div className="jury-heading"><div><h1>{revealed?"Votes revealed together.":"VOTES SEALED"}</h1><p>Same admissible facts. Three neutral presentation structures.</p></div><span className={`seal-state ${revealed?"open":""}`}><Icon name={revealed?"check":"lock"} size={16}/>{revealed?"REVEALED":"SEALED"}</span></div><div className={`jury-grid ${revealed?"revealed":""}`}>{votes.map((vote,index)=><article key={vote.jurorId}><div className="chamber-label"><span>JUROR {index+1}</span><small>{viewLabels[vote.view]}</small></div><div className="sealed-vote"><Icon name="lock" size={28}/><span>VOTE SEALED</span></div><div className="revealed-vote"><strong>{vote.vote.replace("_"," ")}</strong><small><Icon name="check" size={12}/> Stateless · independent</small></div></article>)}</div>{revealed&&<div className="jury-result"><div><span>JURY VERDICT</span><strong>{(verdict?.split??"2–1 overturn").toUpperCase()}</strong></div><div className="safeguard"><Icon name="alert" size={19}/><p><strong>HUMAN REVIEW REQUIRED</strong><span>Factual issue + counterfactual sensitivity</span></p></div><Button onClick={next}>Open judicial review</Button></div>}</div>
}

function HumanJudge({scenario,run,decide}:{scenario:ScenarioDefinition;run:DemoRunResult|null;decide:(decision:HumanDecision)=>void}){
  const record=(action:HumanDecision["action"],reason:string)=>decide(HumanDecisionSchema.parse({action,reason,decidedBy:"A. Korhonen · Human reviewer",decidedAt:new Date().toISOString()}));
  return <div className="screen judge-screen"><section><Kicker>Human oversight</Kicker><h1>A human makes the <span>final decision.</span></h1><div className="verdict-box"><span>JURY VERDICT</span><strong>{(run?.review.court.juryVerdict.split??"2–1 overturn").toUpperCase()}</strong></div><div className="why-called"><span>WHY YOU WERE CALLED</span>{scenario.judgeIssues.map((issue)=><p key={issue}><Icon name="alert" size={17}/>{issue}</p>)}<p><Icon name="shield" size={17}/> Mandatory safeguard triggered</p></div></section><section className="judge-actions"><div className="judge-avatar">AK</div><h2>Record accountable judgment</h2><p>The jury advises. The human remains final authority.</p><button className="accept-action" onClick={()=>record("overridden",`Accepted jury outcome for ${scenario.title}; verified evidence and material risk require the automated decision to be overturned.`)}><span><Icon name="check" size={19}/> Accept Jury Outcome</span><small>OVERTURN AUTOMATED DECISION</small></button><button onClick={()=>record("approved","Original automated outcome retained after independent human review.")}><Icon name="gavel" size={17}/> Uphold Original Decision</button><button onClick={()=>record("review_requested","Additional evidence and specialist review requested before final disposition.")}><Icon name="refresh" size={17}/> Request Further Review</button><small className="audit-note"><Icon name="lock" size={12}/> Identity, reason, and timestamp are recorded</small></section></div>
}

function FinalReport({scenario,zone,run,decision,restart}:{scenario:ScenarioDefinition;zone:ProcessingZoneId;run:DemoRunResult|null;decision:HumanDecision;restart:()=>void}){
  const approved=decision.action==="overridden";const compliance=run?.compliance;const zoneInfo=processingZones.find((item)=>item.id===zone)??processingZones[0];
  const controls=["Data minimization","Purpose limitation","Least-privilege access","Human oversight","Evidence traceability","Fairness checking","Sensitive-field controls","Stateless processing"];
  return <div className="screen report-screen"><header><div><Kicker>Case closed · Audit record</Kicker><h1>{approved?"OVERTURNED":"REVIEW RECORDED"}</h1><p>{scenario.title} · {scenario.caseData.id}</p></div><span className="report-seal"><Icon name="check" size={30}/>{approved?"HUMAN APPROVAL":"HUMAN REVIEW"}</span></header><div className="report-grid"><section className="report-decision"><span>FINAL STRUCTURED DECISION</span><strong>{approved?"AUTOMATED DECISION OVERTURNED":decision.action.replace("_"," ").toUpperCase()}</strong><p>{decision.reason}</p><div className="report-flow"><span>AI: {scenario.initialDecisionLabel}</span><i/> <span>Jury: {run?.review.court.juryVerdict.split??"2–1 overturn"}</span><i/><span>Human judgment</span></div></section><section className="report-boundary"><span>DATA SOVEREIGNTY</span><h3><Icon name="globe" size={19}/>{zoneInfo.label}</h3><p>{compliance?.sovereignty_note??zoneInfo.note}</p><dl><div><dt>Raw data leaves boundary</dt><dd>{compliance?.raw_data_leaves_environment?"Live scoped summaries":"No · fallback/local"}</dd></div><div><dt>Shared forward</dt><dd>Derived summaries only</dd></div><div><dt>Retention</dt><dd>Stateless · no response storage</dd></div></dl></section><section className="report-compliance"><div><span>ENTERPRISE GOVERNANCE COVERAGE</span><strong>{controls.length} controls evidenced</strong></div><div className="control-grid">{controls.map((control)=><p key={control}><Icon name="check" size={12}/>{control}</p>)}</div><small>{compliance?.governance_explanation??"Minimum-necessary packets, independent review, traceable evidence, and human authority create an auditable governance layer."}</small></section><section className="report-trace"><span>EVIDENCE & RISK TRACE</span><div>{scenario.evidenceLabels.map((label,index)=><p key={label}><strong>EV-0{index+1}</strong>{label}</p>)}</div><small>Fairness checks: {compliance?.fairness_checks_run.join(" · ")??"Counterfactual · proxy risk · sensitive-field minimization"}</small></section></div><div className="report-footer"><div className="bob-card"><strong>Built with support from IBM Bob</strong><span>Component scaffolding, flow prototyping, and implementation acceleration.</span></div><div className="test-card"><strong>75 / 75</strong><span>GOVERNANCE TESTS PASSED</span></div><Button onClick={restart} secondary icon="refresh">New case</Button></div></div>
}

export function JuryDemo(){
  const [stage,setStage]=useState(0);const [scenarioId,setScenarioId]=useState<ScenarioId>("lending");const [zone,setZone]=useState<ProcessingZoneId>("local_demo");const [run,setRun]=useState<DemoRunResult|null>(null);const [revealed,setRevealed]=useState(false);const [decision,setDecision]=useState<HumanDecision|null>(null);const scenario=scenarios.find((item)=>item.id===scenarioId)??scenarios[0];
  const start=async()=>{setStage(1);setRevealed(false);let nextRun:DemoRunResult|null=null;try{const response=await fetch("/api/agents",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({scenarioId,zoneId:zone})});if(!response.ok)throw new Error();nextRun=DemoRunResultSchema.parse(await response.json())}catch{nextRun=null}setRun(nextRun);await wait(1100);setStage(2);await wait(1600);setStage(3);await wait(1000);setStage(4)};
  const restart=()=>{setStage(0);setRun(null);setRevealed(false);setDecision(null)};
  let content:ReactNode;if(stage===0)content=<CaseSetup scenario={scenario} setScenario={setScenarioId} zone={zone} setZone={setZone} start={start}/>;else if(stage===1)content=<EvidenceSplit scenario={scenario}/>;else if(stage===2)content=<Witnesses scenario={scenario}/>;else if(stage===3)content=<CourtClerk run={run}/>;else if(stage===4)content=<Jury run={run} revealed={revealed} reveal={()=>setRevealed(true)} next={()=>setStage(5)}/>;else if(stage===5)content=<HumanJudge scenario={scenario} run={run} decide={(value)=>{setDecision(value);setStage(6)}}/>;else content=decision?<FinalReport scenario={scenario} zone={zone} run={run} decision={decision} restart={restart}/>:null;
  return <Shell stage={stage} scenario={scenario} mode={run?.review.mode}>{content}</Shell>
}
