"use client";

import { useMemo, useRef, useState, type ReactNode } from "react";
import { processingZones, type DemoRunResult, type ProcessingZoneId } from "@/lib/compliance";
import { scenarios, type ScenarioId } from "@/lib/scenarios";
import { HumanDecisionSchema, type HumanDecision } from "@/lib/schemas";
import { TrialEventSchema, type TrialEvent } from "@/lib/trial-event-schema";

type IconName = "scale" | "arrow" | "check" | "lock" | "alert" | "file" | "gavel" | "shield" | "refresh" | "globe";
function Icon({ name, size = 20 }: { name: IconName; size?: number }) {
  const paths: Record<IconName, ReactNode> = {
    scale:<><path d="M12 3v18M5 6h14M7 6l-4 7h8L7 6ZM17 6l-4 7h8l-4-7ZM8 21h8"/><path d="M3 13c.5 2 2 3 4 3s3.5-1 4-3M13 13c.5 2 2 3 4 3s3.5-1 4-3"/></>, arrow:<path d="M5 12h14M14 7l5 5-5 5"/>, check:<path d="m5 12 4 4L19 6"/>, lock:<><rect x="4" y="10" width="16" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3M12 14v3"/></>, alert:<><path d="M12 3 2.5 20h19L12 3Z"/><path d="M12 9v5M12 17.5v.1"/></>, file:<><path d="M6 2h8l4 4v16H6z"/><path d="M14 2v5h5M9 12h6M9 16h6"/></>, gavel:<><path d="m13 7 4 4M6 14l4 4M8 16l7-7M11 5l2-2 6 6-2 2M4 20h10"/></>, shield:<><path d="M12 3 4.5 6v5.5c0 4.7 3.1 8 7.5 9.5 4.4-1.5 7.5-4.8 7.5-9.5V6L12 3Z"/><path d="m9 12 2 2 4-4"/></>, refresh:<><path d="M20 7v5h-5M4 17v-5h5"/><path d="M6.1 8A7 7 0 0 1 18.5 7M17.9 16A7 7 0 0 1 5.5 17"/></>, globe:<><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a14 14 0 0 1 0 18M12 3a14 14 0 0 0 0 18"/></>,
  };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden>{paths[name]}</svg>;
}

const witnesses=[{role:"decision_witness",name:"Decision Witness",ids:["EV-01","EV-02","EV-03"]},{role:"fact_checker",name:"Fact Checker",ids:["EV-02","EV-03","EV-04"]},{role:"bias_privacy_challenger",name:"Bias & Privacy Challenger",ids:["EV-05"]}] as const;
const jurors=[{id:"J1",label:"Juror I",view:"Evidence-first"},{id:"J2",label:"Juror II",view:"Claim / Evidence"},{id:"J3",label:"Juror III",view:"Contradiction-first"}] as const;
function Brand(){return <div className="brand"><span><Icon name="scale" size={22}/></span><strong>JuryAI</strong></div>}
function has(events:TrialEvent[],type:TrialEvent["type"]){return events.some((event)=>event.type===type)}
function latest(events:TrialEvent[],type:TrialEvent["type"],role?:string){return [...events].reverse().find((event)=>event.type===type&&(!role||event.role===role))}

export function JuryDemo(){
  const [scenarioId,setScenarioId]=useState<ScenarioId>("lending"); const [zone,setZone]=useState<ProcessingZoneId>("eu_trusted"); const [events,setEvents]=useState<TrialEvent[]>([]); const [run,setRun]=useState<DemoRunResult|null>(null); const [running,setRunning]=useState(false); const [decision,setDecision]=useState<HumanDecision|null>(null); const controller=useRef<AbortController|null>(null);
  const scenario=scenarios.find((item)=>item.id===scenarioId)??scenarios[0]; const zoneInfo=processingZones.find((item)=>item.id===zone)??processingZones[0];
  const start=async()=>{controller.current?.abort();const abort=new AbortController();controller.current=abort;setEvents([]);setRun(null);setDecision(null);setRunning(true);try{const response=await fetch("/api/trials/run",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({scenarioId,zoneId:zone}),signal:abort.signal});if(!response.ok||!response.body)throw new Error("Trial stream unavailable");const reader=response.body.getReader();const decoder=new TextDecoder();let buffer="";while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split("\n");buffer=lines.pop()??"";for(const line of lines){if(!line.trim())continue;const event=TrialEventSchema.parse(JSON.parse(line));setEvents((current)=>[...current,event]);if(event.type==="audit_ready"&&event.result)setRun(event.result)}}}catch{if(!abort.signal.aborted)setEvents((current)=>[...current,{type:"trial_completed",sequence:current.length+1,timestamp:new Date().toISOString(),status:"fallback_failed_safely",mode:"fallback"}])}finally{if(!abort.signal.aborted)setRunning(false)}};
  const restart=()=>{controller.current?.abort();setEvents([]);setRun(null);setDecision(null);setRunning(false);window.scrollTo({top:0,behavior:"smooth"})};
  const decide=(action:HumanDecision["action"],reason:string)=>{const next=HumanDecisionSchema.parse({action,reason,decidedBy:"A. Korhonen · Human reviewer",decidedAt:new Date().toISOString()});setDecision(next);setEvents((current)=>[...current,{type:"trial_completed",sequence:current.length+1,timestamp:next.decidedAt,status:`human_${action}`,summary:reason}])};
  if(!events.length&&!running)return <Initial scenarioId={scenarioId} zone={zone} setScenarioId={setScenarioId} setZone={setZone} start={start}/>;
  if(decision&&run)return <FinalRecord scenarioId={scenarioId} zone={zone} events={events} run={run} decision={decision} restart={restart}/>;
  return <main className="courtroom"><header className="court-header"><Brand/><div className="active-case"><span>{scenario.caseData.id}</span><strong>{scenario.title}</strong></div><div className="boundary"><Icon name="globe" size={16}/><span>{zoneInfo.label}</span><i/>{run?.review.mode==="live"?"LIVE AGENTS":"DEMO FALLBACK"}</div></header><section className="trial-grid"><div className="trial-main"><div className="case-strip"><div><span>ORIGINAL AI</span><strong>{scenario.initialDecisionLabel}</strong><small>{scenario.confidence}% confidence</small></div><p>{scenario.reason}</p><div className="trial-live"><i/>{running?"TRIAL IN SESSION":"AUTONOMOUS REVIEW COMPLETE"}</div></div><Evidence events={events} scenarioId={scenarioId}/>{has(events,"witness_started")&&<WitnessArea events={events}/>} {has(events,"counterfactual_completed")&&<Counterfactual scenarioId={scenarioId}/>} {has(events,"clerk_started")&&<Clerk events={events}/>} {has(events,"juror_started")&&<Jury events={events} run={run}/>} {has(events,"human_review_required")&&run&&<HumanJudge scenarioId={scenarioId} run={run} decide={decide}/>}</div><ProcessFeed events={events}/></section></main>
}

function Initial({scenarioId,zone,setScenarioId,setZone,start}:{scenarioId:ScenarioId;zone:ProcessingZoneId;setScenarioId:(id:ScenarioId)=>void;setZone:(id:ProcessingZoneId)=>void;start:()=>void}){const scenario=scenarios.find((item)=>item.id===scenarioId)??scenarios[0];return <main className="opening"><header><Brand/></header><section className="opening-grid"><div className="opening-copy"><p className="eyebrow">AI DECISION ACCOUNTABILITY</p><h1>AI SHOULD NOT BE<br/><span>JUDGE, JURY,</span><br/>AND WITNESS.</h1><p>One decision. Independent evidence. Accountable human judgment.</p></div><div className="docket"><div className="folder-tab">CASE FILE</div><div className="docket-head"><span>{scenario.caseData.id}</span><strong>{scenario.shortLabel.toUpperCase()} REVIEW</strong></div><div className="machine-decision"><small>AUTOMATED DECISION</small><strong>{scenario.initialDecisionLabel.toUpperCase()}</strong><b>{scenario.confidence}%</b><p>{scenario.reason}</p></div><div className="controls"><label>Scenario<select value={scenarioId} onChange={(e)=>setScenarioId(e.target.value as ScenarioId)}>{scenarios.map((item)=><option key={item.id} value={item.id}>{item.shortLabel}</option>)}</select></label><label>Processing<select value={zone} onChange={(e)=>setZone(e.target.value as ProcessingZoneId)}>{processingZones.map((item)=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label></div><button className="trial-cta" onClick={start}><Icon name="scale" size={24}/>PUT DECISION ON TRIAL<Icon name="arrow" size={20}/></button></div></section></main>}

function Title({n,title,copy,right}:{n:string;title:string;copy:string;right?:string}){return <div className="section-title"><span>{n}</span><div><h2>{title}</h2><p>{copy}</p></div>{right&&<b>{right}</b>}</div>}
function Evidence({events,scenarioId}:{events:TrialEvent[];scenarioId:ScenarioId}){const scenario=scenarios.find((item)=>item.id===scenarioId)??scenarios[0];const routed=has(events,"evidence_partitioned");return <section className={`court-section evidence-area ${routed?"active":""}`}><Title n="01" title="Evidence partition" copy="Each document travels only to an authorized chamber." right="INDEPENDENT FIRST · SYNTHESIS SECOND"/><div className="evidence-routing"><div className="evidence-stack">{scenario.evidenceLabels.map((label,index)=>{const id=`EV-0${index+1}`;const done=events.some((e)=>e.type==="evidence_analysis_completed"&&e.evidenceIds?.includes(id));return <article key={id} className={routed?"routed":""}><span>{id}</span><strong>{label}</strong>{done&&<Icon name="check" size={15}/>}</article>})}</div><div className="route-map"><p><b>EV-01</b><i/>Decision</p><p><b>EV-02 · EV-03</b><i/>Decision + Fact</p><p><b>EV-04</b><i/>Fact</p><p><b>EV-05</b><i/>Bias & Privacy</p></div></div></section>}
function WitnessArea({events}:{events:TrialEvent[]}){return <section className="court-section"><Title n="02" title="Isolated witness chambers" copy="Fresh sessions. Other testimony stays hidden."/><div className="witness-chambers">{witnesses.map((w)=>{const complete=latest(events,"witness_completed",w.role);const sealed=latest(events,"finding_sealed",w.role);return <article key={w.role} className={sealed?"sealed":"working"}><header><Icon name="shield" size={19}/><strong>{w.name}</strong><span>{sealed?"SEALED":"REVIEWING"}</span></header><div className="packet">{w.ids.map((id)=><b key={id}>{id}</b>)}</div><p>{complete?.summary??"Examining permitted evidence…"}</p><footer><Icon name="lock" size={13}/>{sealed?"FINDING SEALED":"OTHER TESTIMONY HIDDEN"}</footer></article>})}</div></section>}
function Counterfactual({scenarioId}:{scenarioId:ScenarioId}){const scenario=scenarios.find((item)=>item.id===scenarioId)??scenarios[0];return <section className="counterfactual"><div><span>ORIGINAL INPUT</span><strong>{scenario.sensitivity.label}</strong><p>{scenario.sensitivity.originalValue}</p><b>DECLINE</b></div><Icon name="arrow" size={25}/><div><span>COUNTERFACTUAL TEST</span><strong>{scenario.sensitivity.label}</strong><p>{scenario.sensitivity.removedValue}</p><b>APPROVE</b></div><aside><Icon name="alert" size={22}/><div><strong>OUTCOME CHANGED</strong><p>Counterfactual sensitivity detected. Human review required.</p></div></aside></section>}
function Clerk({events}:{events:TrialEvent[]}){const packet=latest(events,"case_packet_created");return <section className="court-section clerk"><Title n="03" title="Deterministic Court Clerk" copy="Sealed findings become one admissible record."/><div className="clerk-work"><div>{["Validating evidence references","Removing duplicates","Checking provenance","Building admissible CasePacket"].map((step)=><p key={step}><Icon name="check" size={16}/>{step}</p>)}</div><article><Icon name="file" size={31}/><span>CASEPACKET</span><strong>{String(packet?.details?.packetId??"ASSEMBLING")}</strong><b><Icon name="lock" size={14}/>{packet?"SEALED":"IN PROCESS"}</b></article></div></section>}
function Jury({events,run}:{events:TrialEvent[];run:DemoRunResult|null}){const reveal=latest(events,"jury_revealed");const revealed=Boolean(reveal);const streamedVotes=(reveal?.details?.votes as string[]|undefined)??[];const safeguards=events.filter((event)=>event.type==="safeguard_triggered").map((event)=>event.risk).filter(Boolean);return <section className="court-section jury"><Title n="04" title="Independent jury" copy="SAME FACTS · DIFFERENT NEUTRAL VIEWS"/><div className={`juror-chambers ${revealed?"revealed":""}`}>{jurors.map((juror,index)=>{const sealed=latest(events,"juror_vote_sealed",juror.id);const vote=run?.review.court.jurorVotes[index];const streamed=streamedVotes[index]?.split(":")[1];return <article key={juror.id}><header><strong>{juror.label}</strong><span>{juror.view}</span></header>{revealed?<div className="vote"><strong>{(vote?.vote??streamed??"sealed").replace("_"," ")}</strong><p>{vote?.reason??"Independent vote revealed from the sealed session."}</p></div>:<div className="sealed-state"><Icon name="lock" size={27}/><strong>{sealed?"VOTE SEALED":"REVIEWING CASE"}</strong></div>}</article>})}</div>{has(events,"jury_complete")&&!revealed&&<div className="all-sealed">ALL VOTES SEALED</div>}{revealed&&<div className="verdict"><span>JURY VERDICT</span><strong>{String(run?.review.court.juryVerdict.split??reveal?.details?.split??"2–1 overturn").toUpperCase()}</strong></div>}{safeguards.length>0&&<div className="safeguard"><Icon name="alert" size={24}/><div><strong>PROCEDURAL SAFEGUARD TRIGGERED</strong><p>{safeguards.join(" · ")}</p></div><b>HUMAN REVIEW REQUIRED</b></div>}</section>}
function HumanJudge({scenarioId,run,decide}:{scenarioId:ScenarioId;run:DemoRunResult;decide:(action:HumanDecision["action"],reason:string)=>void}){const scenario=scenarios.find((item)=>item.id===scenarioId)??scenarios[0];return <section className="court-section human-court"><div className="judge-summary"><span>FINAL HUMAN AUTHORITY</span><h2>Review the material issues.</h2><div><p><small>ORIGINAL AI</small><strong>{scenario.initialDecisionLabel} · {scenario.confidence}%</strong></p><p><small>JURY</small><strong>{run.review.court.juryVerdict.split}</strong></p></div><ul>{scenario.judgeIssues.map((issue)=><li key={issue}>{issue}</li>)}</ul></div><div className="judge-actions"><button className="primary" onClick={()=>decide("overridden",`Accepted jury outcome: ${scenario.judgeIssues.join("; ")}.`)}><Icon name="check" size={19}/>Accept jury outcome<span>OVERTURN AUTOMATED DECISION</span></button><button onClick={()=>decide("approved","Original decision upheld after independent human review.")}><Icon name="gavel" size={18}/>Uphold original decision</button><button onClick={()=>decide("review_requested","Further evidence requested before final disposition.")}><Icon name="refresh" size={18}/>Request further review</button><p><Icon name="lock" size={13}/>Reviewer, action, time, and reason are recorded.</p></div></section>}
function ProcessFeed({events}:{events:TrialEvent[]}){const feed=useMemo(()=>events.filter((e)=>["trial_started","evidence_partitioned","witness_completed","finding_sealed","counterfactual_completed","case_packet_created","juror_vote_sealed","jury_revealed","safeguard_triggered","human_review_required"].includes(e.type)).slice(-12),[events]);return <aside className="process-feed"><header><span>PROCEDURAL RECORD</span><i/></header>{feed.map((event)=><p key={`${event.sequence}-${event.type}`}><time>{new Date(event.timestamp).toLocaleTimeString([],{hour12:false,hour:"2-digit",minute:"2-digit",second:"2-digit"})}</time><span>{feedLabel(event)}</span></p>)}</aside>}
function feedLabel(event:TrialEvent){const role=event.role?.replaceAll("_"," ");const labels:Partial<Record<TrialEvent["type"],string>>={trial_started:"Case admitted",evidence_partitioned:"Evidence routed by manifest",counterfactual_completed:"Counterfactual sensitivity detected",case_packet_created:"CasePacket sealed",jury_revealed:"Jury votes revealed together",safeguard_triggered:event.risk??"Safeguard triggered",human_review_required:"System paused for human authority"};return labels[event.type]??(event.type==="finding_sealed"?`${role} finding sealed`:event.type==="witness_completed"?`${role} completed · ${event.mode}`:event.type==="juror_vote_sealed"?`${event.role} vote sealed`:event.type.replaceAll("_"," "))}
function FinalRecord({scenarioId,zone,events,run,decision,restart}:{scenarioId:ScenarioId;zone:ProcessingZoneId;events:TrialEvent[];run:DemoRunResult;decision:HumanDecision;restart:()=>void}){const scenario=scenarios.find((item)=>item.id===scenarioId)??scenarios[0];const zoneInfo=processingZones.find((item)=>item.id===zone)??processingZones[0];const final=decision.action==="overridden"?"OVERTURNED":decision.action==="approved"?"UPHELD":"FURTHER REVIEW";const timeline=["AI decision","5 evidence fragments","3 isolated witnesses","Sealed CasePacket","3 independent jurors",run.review.court.juryVerdict.split,"Safeguard","Human decision"];const controls=["Human oversight","Data minimization","Purpose-limited access","Evidence traceability","Independent review","Fairness check","Stateless processing","Human decision recorded"];return <main className="record"><header><Brand/><button onClick={restart}><Icon name="refresh" size={16}/>NEW CASE</button></header><section className="record-title"><p>CASE CLOSED · {scenario.caseData.id}</p><h1>{final}</h1><span><Icon name="check" size={25}/>AUDIT RECORD SEALED</span></section><section className="timeline">{timeline.map((item,index)=><div key={item}><b>{String(index+1).padStart(2,"0")}</b><span>{item}</span></div>)}</section><div className="record-grid"><section><span>ACCOUNTABLE JUDGMENT</span><h2>{decision.reason}</h2><dl><div><dt>Reviewer</dt><dd>{decision.decidedBy}</dd></div><div><dt>Time</dt><dd>{new Date(decision.decidedAt).toLocaleString()}</dd></div><div><dt>Recorded events</dt><dd>{events.length}</dd></div></dl></section><section><span>COMPLIANCE EVIDENCE GENERATED</span><h2>Controls demonstrated</h2><div className="controls-list">{controls.map((control)=><p key={control}><Icon name="check" size={13}/>{control}</p>)}</div></section><section><span>PROCESSING BOUNDARY</span><h2><Icon name="globe" size={21}/>{zoneInfo.label}</h2><p>Raw case data: restricted to configured boundary</p><p>Agent sharing: minimum necessary packets</p><p>Model retention: stateless / store:false where supported</p><small>Regional infrastructure is simulated in this prototype.</small></section><section className="bob"><span>IBM BOB · DEVELOPMENT ASSURANCE</span><p>During development Bob tested our evidence boundaries and caught unnecessary access by the Bias Challenger.</p><div><p><small>BEFORE</small>EV-01 · EV-02 · EV-03 · EV-05</p><Icon name="arrow" size={20}/><p><small>AFTER</small>EV-05 ONLY</p></div><strong>79 / 79 TESTS PASSING</strong><small>No certification or endorsement is implied.</small></section></div></main>}
