import { CaseSchema } from "./schemas";

export const demoCase = CaseSchema.parse({
  id: "JAI-2026-0417",
  title: "Consumer loan eligibility review",
  status: "intake",
  submittedAt: "2026-09-18T09:42:00+03:00",
  applicant: {
    id: "APL-2841",
    name: "Emma Lindholm",
    age: 34,
    occupation: "Operations Manager",
    employmentYears: 6.8,
    monthlyIncomeEur: 5250,
    requestedAmountEur: 18500,
    loanPurpose: "Home energy renovation",
    creditScore: 718,
    debtToIncomeRatio: 0.31,
    postalCode: "00990 Helsinki",
  },
  evidence: [
    {
      id: "EV-01",
      title: "Verified income statement",
      provider: "Northstar Payroll",
      category: "income",
      verified: true,
      collectedAt: "18 Sep 2026 · 09:40",
      summary: "Stable monthly gross income of €5,250 across 24 months.",
      reliability: "high",
      dataPoints: ["Monthly income", "Employment tenure", "Employer status"],
    },
    {
      id: "EV-02",
      title: "Credit bureau record",
      provider: "Nordic Credit Registry",
      category: "credit",
      verified: true,
      collectedAt: "18 Sep 2026 · 09:40",
      summary: "Score 718. No defaults, collections, or missed credit instalments.",
      reliability: "high",
      dataPoints: ["Credit score", "Payment history", "Open credit lines"],
    },
    {
      id: "EV-03",
      title: "Open banking summary",
      provider: "Applicant-authorised feed",
      category: "banking",
      verified: true,
      collectedAt: "18 Sep 2026 · 09:41",
      summary: "31% debt-to-income ratio; two utility transfers posted 48 hours late in May.",
      reliability: "high",
      dataPoints: ["Debt-to-income", "Account cashflow", "Payment timestamps"],
    },
    {
      id: "EV-04",
      title: "Bank migration notice",
      provider: "Aurora Bank",
      category: "context",
      verified: true,
      collectedAt: "18 Sep 2026 · 09:41",
      summary: "Confirms May payment delays affected scheduled transfers during an account migration.",
      reliability: "high",
      dataPoints: ["Migration window", "Affected transfers", "Settlement status"],
    },
    {
      id: "EV-05",
      title: "Application profile",
      provider: "Direct application",
      category: "applicant",
      verified: true,
      collectedAt: "18 Sep 2026 · 09:39",
      summary: "Identity, contact address, requested amount, and declared loan purpose.",
      reliability: "medium",
      dataPoints: ["Age", "Postal code", "Loan purpose", "Requested amount"],
    },
  ],
  initialDecision: {
    recommendation: "decline",
    confidence: 0.86,
    model: "Northstar Lending Model v4.2",
    rationale: [
      "Recent payment instability indicates elevated near-term repayment risk.",
      "Local default-risk index exceeds the lender's preferred threshold.",
      "Requested exposure is high relative to recent liquid reserves.",
    ],
    dataUsed: ["Income", "Credit file", "Open banking", "Postal-risk index", "Cash reserves"],
  },
});

